name: BrandBlocker
version: ${project.version}
main: dev.victormenacho.brandblocker.BrandBlocker
authors: [ Menacho, mercurialmusic ]
description: Block any client brand easily.
website: victormenacho.dev
api-version: "1.21"
commands:
  brandblocker:
    description: BrandBlocker main command.
    default: op
