plugins {
    id 'java-library'
}

dependencies {
    implementation project(':guardian-core')
    implementation project(':guardian-protocol')
    compileOnly "io.papermc.paper:paper-api:${paper_api_version}"
    compileOnly "org.geysermc.floodgate:api:${floodgate_api_version}"

    testImplementation platform('org.junit:junit-bom:5.13.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

base {
    archivesName = 'guardian-paper'
}

tasks.named('jar') {
    dependsOn project(':guardian-core').tasks.named('classes')
    dependsOn project(':guardian-protocol').tasks.named('classes')
    from(project(':guardian-core').sourceSets.main.output)
    from(project(':guardian-protocol').sourceSets.main.output)
}

def guardianVersion = version.toString()

processResources {
    inputs.property 'version', guardianVersion
    filesMatching('plugin.yml') {
        expand version: guardianVersion
    }
}
